"use client";

import { db } from "./firebase";
import { collection, doc, setDoc, getDocs } from "firebase/firestore";

// Minimal but complete data
const minimalData = {
  categories: [
    { id: "cat-starters", name: "Starters", description: "Appetizers & Small Plates", itemCount: 3, active: true },
    { id: "cat-mains", name: "Main Course", description: "Hearty Main Dishes", itemCount: 4, active: true },
    { id: "cat-desserts", name: "Desserts", description: "Sweet Treats", itemCount: 2, active: true },
    { id: "cat-beverages", name: "Beverages", description: "Drinks", itemCount: 4, active: true },
  ],
  menuItems: [
    // Starters
    {
      id: "m-garlic-bread",
      name: "Garlic Bread",
      description: "Fresh baked bread with garlic butter",
      categoryId: "cat-starters",
      price: 199,
      cost: 50,
      prepTime: 8,
      available: true,
      vegetarian: true,
      spicy: 0,
      popular: true,
      soldToday: 0,
      soldWeek: 0,
      ingredients: ["ing-bread", "ing-garlic", "ing-butter"],
    },
    {
      id: "m-calamari",
      name: "Crispy Calamari",
      description: "Fried calamari rings with marinara sauce",
      categoryId: "cat-starters",
      price: 399,
      cost: 150,
      prepTime: 12,
      available: true,
      vegetarian: false,
      spicy: 0,
      popular: true,
      soldToday: 0,
      soldWeek: 0,
      ingredients: ["ing-calamari", "ing-flour"],
    },
    {
      id: "m-bruschetta",
      name: "Bruschetta",
      description: "Toasted bread with tomato, basil, and olive oil",
      categoryId: "cat-starters",
      price: 249,
      cost: 70,
      prepTime: 10,
      available: true,
      vegetarian: true,
      spicy: 0,
      popular: false,
      soldToday: 0,
      soldWeek: 0,
      ingredients: ["ing-bread", "ing-tomato", "ing-basil"],
    },

    // Main Course
    {
      id: "m-grilled-chicken",
      name: "Grilled Chicken",
      description: "Juicy grilled chicken breast with vegetables",
      categoryId: "cat-mains",
      price: 599,
      cost: 200,
      prepTime: 18,
      available: true,
      vegetarian: false,
      spicy: 0,
      popular: true,
      soldToday: 0,
      soldWeek: 0,
      ingredients: ["ing-chicken", "ing-vegetables"],
    },
    {
      id: "m-salmon",
      name: "Pan-Seared Salmon",
      description: "Atlantic salmon with lemon butter sauce",
      categoryId: "cat-mains",
      price: 799,
      cost: 300,
      prepTime: 15,
      available: true,
      vegetarian: false,
      spicy: 0,
      popular: true,
      soldToday: 0,
      soldWeek: 0,
      ingredients: ["ing-salmon", "ing-lemon", "ing-butter"],
    },
    {
      id: "m-spaghetti",
      name: "Spaghetti Carbonara",
      description: "Classic pasta with bacon, egg, and parmesan",
      categoryId: "cat-mains",
      price: 499,
      cost: 180,
      prepTime: 14,
      available: true,
      vegetarian: false,
      spicy: 0,
      popular: true,
      soldToday: 0,
      soldWeek: 0,
      ingredients: ["ing-pasta", "ing-bacon", "ing-parmesan"],
    },
    {
      id: "m-veggie-risotto",
      name: "Vegetable Risotto",
      description: "Creamy risotto with seasonal vegetables",
      categoryId: "cat-mains",
      price: 449,
      cost: 130,
      prepTime: 20,
      available: true,
      vegetarian: true,
      spicy: 0,
      popular: false,
      soldToday: 0,
      soldWeek: 0,
      ingredients: ["ing-rice", "ing-vegetables", "ing-parmesan"],
    },

    // Desserts
    {
      id: "m-tiramisu",
      name: "Tiramisu",
      description: "Classic Italian tiramisu",
      categoryId: "cat-desserts",
      price: 299,
      cost: 100,
      prepTime: 5,
      available: true,
      vegetarian: true,
      spicy: 0,
      popular: true,
      soldToday: 0,
      soldWeek: 0,
      ingredients: ["ing-coffee", "ing-mascarpone", "ing-cocoa"],
    },
    {
      id: "m-lava-cake",
      name: "Chocolate Lava Cake",
      description: "Warm chocolate cake with molten center",
      categoryId: "cat-desserts",
      price: 349,
      cost: 120,
      prepTime: 12,
      available: true,
      vegetarian: true,
      spicy: 0,
      popular: true,
      soldToday: 0,
      soldWeek: 0,
      ingredients: ["ing-chocolate", "ing-flour", "ing-eggs"],
    },

    // Beverages
    {
      id: "m-iced-tea",
      name: "Iced Tea",
      description: "Fresh brewed iced tea",
      categoryId: "cat-beverages",
      price: 99,
      cost: 20,
      prepTime: 2,
      available: true,
      vegetarian: true,
      spicy: 0,
      popular: true,
      soldToday: 0,
      soldWeek: 0,
      ingredients: [],
    },
    {
      id: "m-lemonade",
      name: "Lemonade",
      description: "Fresh squeezed lemonade",
      categoryId: "cat-beverages",
      price: 129,
      cost: 30,
      prepTime: 3,
      available: true,
      vegetarian: true,
      spicy: 0,
      popular: false,
      soldToday: 0,
      soldWeek: 0,
      ingredients: ["ing-lemon"],
    },
    {
      id: "m-espresso",
      name: "Espresso",
      description: "Rich Italian espresso",
      categoryId: "cat-beverages",
      price: 99,
      cost: 15,
      prepTime: 1,
      available: true,
      vegetarian: true,
      spicy: 0,
      popular: false,
      soldToday: 0,
      soldWeek: 0,
      ingredients: ["ing-coffee"],
    },
    {
      id: "m-water",
      name: "Sparkling Water",
      description: "Refreshing sparkling water",
      categoryId: "cat-beverages",
      price: 79,
      cost: 10,
      prepTime: 0,
      available: true,
      vegetarian: true,
      spicy: 0,
      popular: false,
      soldToday: 0,
      soldWeek: 0,
      ingredients: [],
    },
  ],
  tables: [
    { id: "t-1", number: "1", capacity: 2, status: "vacant", section: "Main" },
    { id: "t-2", number: "2", capacity: 4, status: "vacant", section: "Main" },
    { id: "t-3", number: "3", capacity: 2, status: "vacant", section: "Window" },
    { id: "t-4", number: "4", capacity: 6, status: "vacant", section: "Main" },
    { id: "t-5", number: "5", capacity: 4, status: "vacant", section: "Window" },
  ],
  staff: [
    {
      id: "s-manager",
      name: "Manager",
      email: "manager@restaurant.com",
      phone: "+1 555-1000",
      role: "manager",
      status: "active",
      shift: "day",
      hourlyRate: 35,
      hiredAt: new Date().toISOString(),
    },
    {
      id: "s-waiter1",
      name: "John Waiter",
      email: "john@restaurant.com",
      phone: "+1 555-1001",
      role: "waiter",
      status: "active",
      shift: "day",
      hourlyRate: 18,
      hiredAt: new Date().toISOString(),
    },
    {
      id: "s-chef1",
      name: "Maria Chef",
      email: "maria@restaurant.com",
      phone: "+1 555-1002",
      role: "chef",
      status: "active",
      shift: "day",
      hourlyRate: 28,
      hiredAt: new Date().toISOString(),
    },
    {
      id: "s-delivery1",
      name: "Mike Delivery",
      email: "mike@restaurant.com",
      phone: "+1 555-1003",
      role: "delivery",
      status: "active",
      shift: "day",
      hourlyRate: 16,
      hiredAt: new Date().toISOString(),
    },
  ],
  ingredients: [
    {
      id: "ing-bread",
      name: "Bread",
      category: "other",
      stock: 30,
      unit: "pcs",
      par: 50,
      reorderLevel: 10,
      costPerUnit: 0.5,
      supplier: "Bakery Co.",
    },
    {
      id: "ing-garlic",
      name: "Garlic",
      category: "produce",
      stock: 45,
      unit: "cloves",
      par: 100,
      reorderLevel: 20,
      costPerUnit: 0.1,
      supplier: "Fresh Produce Inc.",
    },
    {
      id: "ing-butter",
      name: "Butter",
      category: "dairy",
      stock: 15,
      unit: "lbs",
      par: 30,
      reorderLevel: 5,
      costPerUnit: 3.5,
      supplier: "Dairy Fresh",
    },
    {
      id: "ing-calamari",
      name: "Calamari",
      category: "meat",
      stock: 10,
      unit: "lbs",
      par: 25,
      reorderLevel: 5,
      costPerUnit: 8.5,
      supplier: "Seafood Market",
    },
    {
      id: "ing-flour",
      name: "Flour",
      category: "grains",
      stock: 40,
      unit: "lbs",
      par: 60,
      reorderLevel: 15,
      costPerUnit: 1.2,
      supplier: "Grain Pro",
    },
    {
      id: "ing-tomato",
      name: "Tomatoes",
      category: "produce",
      stock: 35,
      unit: "pcs",
      par: 80,
      reorderLevel: 20,
      costPerUnit: 0.8,
      supplier: "Fresh Produce Inc.",
    },
    {
      id: "ing-basil",
      name: "Basil",
      category: "produce",
      stock: 8,
      unit: "bunches",
      par: 20,
      reorderLevel: 5,
      costPerUnit: 2.0,
      supplier: "Fresh Produce Inc.",
    },
    {
      id: "ing-chicken",
      name: "Chicken Breast",
      category: "meat",
      stock: 20,
      unit: "lbs",
      par: 40,
      reorderLevel: 10,
      costPerUnit: 4.5,
      supplier: "Meat Pro",
    },
    {
      id: "ing-vegetables",
      name: "Mixed Vegetables",
      category: "produce",
      stock: 25,
      unit: "lbs",
      par: 45,
      reorderLevel: 10,
      costPerUnit: 2.5,
      supplier: "Fresh Produce Inc.",
    },
    {
      id: "ing-salmon",
      name: "Atlantic Salmon",
      category: "meat",
      stock: 12,
      unit: "lbs",
      par: 25,
      reorderLevel: 6,
      costPerUnit: 12.0,
      supplier: "Seafood Market",
    },
    {
      id: "ing-lemon",
      name: "Lemon",
      category: "produce",
      stock: 40,
      unit: "pcs",
      par: 70,
      reorderLevel: 20,
      costPerUnit: 0.6,
      supplier: "Fresh Produce Inc.",
    },
    {
      id: "ing-pasta",
      name: "Spaghetti",
      category: "grains",
      stock: 30,
      unit: "lbs",
      par: 50,
      reorderLevel: 15,
      costPerUnit: 1.8,
      supplier: "Grain Pro",
    },
    {
      id: "ing-bacon",
      name: "Bacon",
      category: "meat",
      stock: 18,
      unit: "lbs",
      par: 35,
      reorderLevel: 8,
      costPerUnit: 5.0,
      supplier: "Meat Pro",
    },
    {
      id: "ing-parmesan",
      name: "Parmesan Cheese",
      category: "dairy",
      stock: 10,
      unit: "lbs",
      par: 20,
      reorderLevel: 4,
      costPerUnit: 8.0,
      supplier: "Dairy Fresh",
    },
    {
      id: "ing-rice",
      name: "Arborio Rice",
      category: "grains",
      stock: 20,
      unit: "lbs",
      par: 40,
      reorderLevel: 10,
      costPerUnit: 3.0,
      supplier: "Grain Pro",
    },
    {
      id: "ing-coffee",
      name: "Coffee Beans",
      category: "beverages",
      stock: 8,
      unit: "lbs",
      par: 15,
      reorderLevel: 4,
      costPerUnit: 12.0,
      supplier: "Coffee Co.",
    },
    {
      id: "ing-mascarpone",
      name: "Mascarpone Cheese",
      category: "dairy",
      stock: 6,
      unit: "lbs",
      par: 12,
      reorderLevel: 3,
      costPerUnit: 6.0,
      supplier: "Dairy Fresh",
    },
    {
      id: "ing-cocoa",
      name: "Cocoa Powder",
      category: "other",
      stock: 4,
      unit: "lbs",
      par: 10,
      reorderLevel: 2,
      costPerUnit: 4.5,
      supplier: "Bakery Co.",
    },
    {
      id: "ing-chocolate",
      name: "Dark Chocolate",
      category: "other",
      stock: 8,
      unit: "lbs",
      par: 15,
      reorderLevel: 3,
      costPerUnit: 5.0,
      supplier: "Bakery Co.",
    },
    {
      id: "ing-eggs",
      name: "Eggs",
      category: "dairy",
      stock: 60,
      unit: "pcs",
      par: 120,
      reorderLevel: 30,
      costPerUnit: 0.3,
      supplier: "Dairy Fresh",
    },
  ],
  orders: [],
  customers: [],
  deliveries: [],
  activity: [],
  reservations: [],
  revenueByDay: [],
};

export async function initializeFirebase() {
  try {
    // Check if data already exists
    const categoriesSnapshot = await getDocs(collection(db, "categories"));

    if (!categoriesSnapshot.empty) {
      console.log("Firebase already has data - skipping initialization");
      return;
    }

    console.log("Initializing Firebase with minimal data...");

    // Add categories
    for (const category of minimalData.categories) {
      await setDoc(doc(db, "categories", category.id), category);
    }

    // Add menu items
    for (const item of minimalData.menuItems) {
      await setDoc(doc(db, "menuItems", item.id), item);
    }

    // Add tables
    for (const table of minimalData.tables) {
      await setDoc(doc(db, "tables", table.id), table);
    }

    // Add staff
    for (const staff of minimalData.staff) {
      await setDoc(doc(db, "staff", staff.id), staff);
    }

    // Add ingredients
    for (const ingredient of minimalData.ingredients) {
      await setDoc(doc(db, "ingredients", ingredient.id), ingredient);
    }

    console.log("✅ Firebase initialized successfully with minimal data!");
  } catch (error) {
    console.error("Error initializing Firebase:", error);
  }
}
